apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oke-cluster-start-stop
spec:
  version: "v1.0.4"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: https://github.com/javiermugueta/oke-cluster-start-stop/blob/master/oke-cluster-start-stop-1.0.4.zip
    sha256: "54f50a801ba7cd568d7ff5e7295207a5a2e5d003c58bc39d28a768030cdaf809"
    files:
    - from: "./kubectl-oke-cluster-start-stop"
      to: "."
    bin: "./kubectl-oke-cluster-start-stop"
  shortDescription: Starts/stops compute nodes in OKE cluster.
  homepage: https://github.com/javiermugueta/oke-cluster-start-stop 
  caveats: |
    This plugin needs the following programs:
    * homebrew
    * jq (it is installed automatically in case it is not)
  description: |
    This plugin starts or stops all the compute nodes of a k8s cluster in Oracle Kubernetes Engine (OKE).